apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $PROJECT_ID
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: $NGINX_IMAGE
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-sites
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: $BUCKET_NAME
            mountOptions: only-dir=config/nginx/conf.d
      - name: nginx-sites
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: $BUCKET_NAME
            mountOptions: only-dir=sites
